[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "endstone-joker"
version = "0.1.1"

[project.entry-points."endstone"]
joker = "endstone_joker:Joker"